apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-pre-install
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: flowlet/backend:latest # Use your application image with migration capabilities
        command: ["/bin/sh", "-c", "echo 'Running pre-install database migrations...' && sleep 10"]
        # Replace with actual migration command, e.g., python manage.py migrate
---
apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-post-upgrade
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: flowlet/backend:latest # Use your application image with migration capabilities
        command: ["/bin/sh", "-c", "echo 'Running post-upgrade database migrations...' && sleep 10"]
        # Replace with actual migration command, e.g., python manage.py migrate


