apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  ports:
  - name: web
    port: 9093
    targetPort: 9093
  selector:
    app: alertmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.27.0
        args:
          - --config.file=/etc/alertmanager/config.yml
          - --storage.path=/alertmanager
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: storage-volume
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      - name: storage-volume
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname", "cluster", "service"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: "null"
    receivers:
      - name: "null"
    # Example of a basic alert rule for Prometheus
    # This would typically be in a separate PrometheusRule object
    # apiVersion: monitoring.coreos.com/v1
    # kind: PrometheusRule
    # metadata:
    #   name: kubernetes-alerts
    #   namespace: monitoring
    # spec:
    #   groups:
    #   - name: kubernetes.rules
    #     rules:
    #     - alert: KubePodCrashLooping
    #       expr: sum(increase(kube_pod_container_status_restarts_total[5m])) by (namespace, pod, container) > 0
    #       for: 1m
    #       labels:
    #         severity: warning
    #       annotations:
    #         summary: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is crashlooping


