apiVersion: opentelemetry.io/v1alpha1
kind: Jaeger
metadata:
  name: jaeger-all-in-one
  namespace: monitoring
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.52.0
    options:
      query.base-path: /jaeger
  ingress:
    enabled: true
    hosts:
      - jaeger.example.com
    tls:
      - hosts:
          - jaeger.example.com
        secretName: jaeger-tls-secret


