apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: flowlet-core
data:
  application.yml: |
    server:
      port: 8080
    services:
      wallet:
        url: http://wallet-service.flowlet-core.svc.cluster.local
      payments:
        url: http://payments-service.flowlet-core.svc.cluster.local
      cards:
        url: http://card-service.flowlet-core.svc.cluster.local
      kyc:
        url: http://kyc-aml-service.flowlet-core.svc.cluster.local
      ledger:
        url: http://ledger-service.flowlet-core.svc.cluster.local
      auth:
        url: http://auth-service.flowlet-core.svc.cluster.local
      notifications:
        url: http://notification-service.flowlet-core.svc.cluster.local
    redis:
      host: redis.flowlet-data.svc.cluster.local
      port: 6379
    cors:
      allowedOrigins: "*"
      allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
      allowedHeaders: "*"
    rateLimit:
      requests: 1000
      window: 60000
    logging:
      level: info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: flowlet-core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: flowlet/api-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: password
        volumeMounts:
        - name: config
          mountPath: /app/config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: flowlet-core
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer

