apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-service-config
  namespace: flowlet-core
data:
  application.yml: |
    server:
      port: 3000
    database:
      host: postgresql.flowlet-data.svc.cluster.local
      port: 5432
      name: flowlet
      username: flowlet
    redis:
      host: redis.flowlet-data.svc.cluster.local
      port: 6379
    kafka:
      brokers: kafka-0.kafka.flowlet-messaging.svc.cluster.local:9092,kafka-1.kafka.flowlet-messaging.svc.cluster.local:9092,kafka-2.kafka.flowlet-messaging.svc.cluster.local:9092
    logging:
      level: info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: flowlet-core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
      - name: wallet-service
        image: flowlet/wallet-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: password
        volumeMounts:
        - name: config
          mountPath: /app/config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: wallet-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  namespace: flowlet-core
spec:
  selector:
    app: wallet-service
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP

