apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowlet.fullname" . }}-secrets
  labels:
    {{- include "flowlet.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "flowlet.databaseUrl" . | b64enc }}
  redis-url: {{ include "flowlet.redisUrl" . | b64enc }}
  jwt-secret: {{ .Values.backend.env.JWT_SECRET | b64enc }}

