
name: Documentation Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  pull_request:
    branches:
      - main
    paths:
      - docs/**

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install documentation dependencies
      run: |
        pip install sphinx sphinx-rtd-theme
        # Add any other documentation tool installations here, e.g., mkdocs

    - name: Build documentation
      run: sphinx-build -b html docs/source docs/build
      # Adjust this command based on the actual documentation tool used (e.g., mkdocs build)

    - name: Deploy documentation to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build
        # Adjust publish_dir if your documentation build output is in a different location


